#Requires -Version 5.1
# elf_gallery.ps1 — Auto-generate visualization gallery markdown
# Scans 64_Viz/ for images, groups by session, outputs _gallery.md

$ErrorActionPreference = "Stop"

# Use git to find the repository root
try {
    $RepoRoot = git rev-parse --show-toplevel
} catch {
    Write-Host "[Gallery] Error: Git command failed. Not a git repository?" -ForegroundColor Red
    exit 1
}

$VizDir = Join-Path $RepoRoot "6_Exp\64_Viz"
$Gallery = Join-Path $VizDir "_gallery.md"

if (-Not (Test-Path $VizDir -PathType Container)) {
    Write-Host "[Gallery] 64_Viz/ not found" -ForegroundColor Yellow
    exit 1
}

$OutputLines = @(
    "# Visualization Gallery"
    ""
    "> Auto-generated by elf_gallery.ps1. Do not edit manually."
    "> Last updated: $(Get-Date -Format 'yyyy-MM-dd HH:mm')"
    ""
)

$nImages = 0
$nSessions = 0

$SessionDirs = Get-ChildItem -Path $VizDir -Directory | Sort-Object Name

foreach ($Dir in $SessionDirs) {
    # Get all graphical files in this session directory
    $Images = Get-ChildItem -Path $Dir.FullName -File | Where-Object { $_.Extension -match "\.(png|jpg|svg)$" } | Sort-Object Name
    
    if ($Images.Count -gt 0) {
        $nSessions++
        $OutputLines += "## $($Dir.Name)"
        $OutputLines += ""
        
        foreach ($Img in $Images) {
            $nImages++
            $BaseName = [System.IO.Path]::GetFileNameWithoutExtension($Img.Name)
            $OutputLines += "![${BaseName}]($($Dir.Name)/$($Img.Name))"
            $OutputLines += ""
        }
    }
}

# Output file with UTF-8 encoding (no BOM)
[System.IO.File]::WriteAllLines($Gallery, $OutputLines, [System.Text.Encoding]::UTF8)

Write-Host "[Gallery] Generated: $nSessions sessions, $nImages images" -ForegroundColor Green
