#!/bin/bash
# elf_gallery.sh — Auto-generate visualization gallery markdown
# Scans 54_Viz/ for images, groups by session, outputs _gallery.md

REPO_ROOT="$(git rev-parse --show-toplevel)"
VIZ_DIR="$REPO_ROOT/5_Exp/54_Viz"
GALLERY="$VIZ_DIR/_gallery.md"

if [ ! -d "$VIZ_DIR" ]; then
    echo "[Gallery] 54_Viz/ not found"
    exit 1
fi

{
    echo "# Visualization Gallery"
    echo ""
    echo "> Auto-generated by elf_gallery.sh. Do not edit manually."
    echo "> Last updated: $(date '+%Y-%m-%d %H:%M')"
    echo ""

    # Find all session directories, sorted
    for session_dir in $(find "$VIZ_DIR" -mindepth 1 -maxdepth 1 -type d | sort); do
        session_name=$(basename "$session_dir")

        # Collect image files
        images=$(find "$session_dir" -maxdepth 1 -type f \( -name "*.png" -o -name "*.jpg" -o -name "*.svg" \) | sort)

        if [ -n "$images" ]; then
            echo "## $session_name"
            echo ""
            while IFS= read -r img; do
                fname=$(basename "$img")
                echo "![${fname%.*}](${session_name}/${fname})"
                echo ""
            done <<< "$images"
        fi
    done
} > "$GALLERY"

# Count
n_images=$(find "$VIZ_DIR" -mindepth 2 -type f \( -name "*.png" -o -name "*.jpg" -o -name "*.svg" \) | wc -l)
n_sessions=$(find "$VIZ_DIR" -mindepth 1 -maxdepth 1 -type d | wc -l)
echo "[Gallery] Generated: $n_sessions sessions, $n_images images"
