//! `elf gallery` — `6_Exp/64_Viz/` 스캔 → 세션별 그룹 → `_gallery.md` 생성 (P012 t03).
//!
//! 구 셸/PS 스크립트(`scripts/elf_gallery.{sh,ps1}`, 본 이관으로 제거)를 대체. 렌더는 순수(타임스탬프 주입)로 분리해
//! FS 없이 출력 포맷을 전수 검증. 64_Viz 부재 시 안내 후 정상 종료(exit 0).

use std::fs;
use std::io;
use std::path::{Path, PathBuf};

#[derive(Debug, Default, PartialEq, Eq)]
pub struct GalleryResult {
    /// `6_Exp/64_Viz/` 존재 여부 (없으면 안내 후 정상 종료)
    pub viz_present: bool,
    /// 이미지를 1개 이상 가진 세션 디렉토리 수
    pub sessions: usize,
    pub images: usize,
    pub output_rel: String,
}

/// png/jpg/svg (대소문자 무관).
fn is_image(name: &str) -> bool {
    let lower = name.to_ascii_lowercase();
    lower.ends_with(".png") || lower.ends_with(".jpg") || lower.ends_with(".svg")
}

/// 세션별 (이름, 이미지파일들) → `_gallery.md` 마크다운 (순수). `now` = "YYYY-MM-DD HH:MM" 주입.
pub fn render_gallery(groups: &[(String, Vec<String>)], now: &str) -> String {
    let mut out = String::new();
    out.push_str("# Visualization Gallery\n\n");
    out.push_str("> Auto-generated by `elf gallery`. Do not edit manually.\n");
    out.push_str(&format!("> Last updated: {now}\n\n"));
    for (name, images) in groups {
        out.push_str(&format!("## {name}\n\n"));
        for img in images {
            let stem = img.rsplit_once('.').map_or(img.as_str(), |(s, _)| s);
            out.push_str(&format!("![{stem}]({name}/{img})\n\n"));
        }
    }
    out
}

/// 디렉토리의 이미지 파일명을 이름순으로 수집.
fn images_in(dir: &Path) -> io::Result<Vec<String>> {
    let mut imgs = Vec::new();
    for e in fs::read_dir(dir)? {
        let e = e?;
        if e.file_type()?.is_file() {
            let name = e.file_name().to_string_lossy().into_owned();
            if is_image(&name) {
                imgs.push(name);
            }
        }
    }
    imgs.sort();
    Ok(imgs)
}

/// `elf gallery`: 64_Viz 스캔 → 세션별 그룹 → `_gallery.md` 작성. `now` 주입(테스트 결정성).
pub fn run_gallery(root: &Path, now: &str) -> io::Result<GalleryResult> {
    let viz = root.join("6_Exp").join("64_Viz");
    let output_rel = "6_Exp/64_Viz/_gallery.md".to_string();
    if !viz.is_dir() {
        return Ok(GalleryResult { viz_present: false, output_rel, ..Default::default() });
    }

    // 1단계 하위 디렉토리 = 세션, 이름순
    let mut dirs: Vec<(String, PathBuf)> = Vec::new();
    for e in fs::read_dir(&viz)? {
        let e = e?;
        if e.file_type()?.is_dir() {
            dirs.push((e.file_name().to_string_lossy().into_owned(), e.path()));
        }
    }
    dirs.sort_by(|a, b| a.0.cmp(&b.0));

    let mut groups: Vec<(String, Vec<String>)> = Vec::new();
    let mut images = 0;
    for (name, path) in &dirs {
        let imgs = images_in(path)?;
        if !imgs.is_empty() {
            images += imgs.len();
            groups.push((name.clone(), imgs));
        }
    }

    fs::write(viz.join("_gallery.md"), render_gallery(&groups, now))?;
    Ok(GalleryResult { viz_present: true, sessions: groups.len(), images, output_rel })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn is_image_matches_png_jpg_svg_case_insensitive() {
        assert!(is_image("fig.png"));
        assert!(is_image("a.JPG"));
        assert!(is_image("b.Svg"));
        assert!(!is_image("notes.md"));
        assert!(!is_image("data.csv"));
        assert!(!is_image("_gallery.md"));
    }

    #[test]
    fn render_groups_with_header_and_stems() {
        let groups = vec![
            ("S001".to_string(), vec!["sweep.png".to_string(), "fit.v2.svg".to_string()]),
            ("S002".to_string(), vec!["map.jpg".to_string()]),
        ];
        let md = render_gallery(&groups, "2026-06-13 09:30");
        assert!(md.starts_with("# Visualization Gallery\n\n"));
        assert!(md.contains("> Auto-generated by `elf gallery`. Do not edit manually.\n"));
        assert!(md.contains("> Last updated: 2026-06-13 09:30\n"));
        assert!(md.contains("## S001\n\n"));
        assert!(md.contains("![sweep](S001/sweep.png)\n\n"));
        assert!(md.contains("![fit.v2](S001/fit.v2.svg)\n\n")); // 마지막 확장자만 제거
        assert!(md.contains("## S002\n\n"));
        assert!(md.contains("![map](S002/map.jpg)\n\n"));
    }

    #[test]
    fn render_empty_is_header_only() {
        let md = render_gallery(&[], "2026-06-13 09:30");
        assert!(md.contains("# Visualization Gallery"));
        assert!(!md.contains("## "));
    }
}
